replicaCount: 1
image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

postgresDatabase: springdb
postgresUser: postgres
postgresPassword: postgres

service:
  type: ClusterIP
  port: 5432
