apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}-app
spec:
  type: {{ .Values.service.app.type }}
  selector:
    app: {{ include "springboot-app.fullname" . }}-app
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.service.app.nodePort | default 30080 }}
