apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}-postgres
spec:
  type: {{ .Values.service.postgres.type }}
  selector:
    app: {{ include "springboot-app.fullname" . }}-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
